### ISSUE TITLE
SonarQube 9.0 fails to load sonar-groovy with NoClassDefFoundError: org/sonar/api/profiles/ProfileDefinition

### ISSUE THREAD

**Issue by boardend** [Inform-Software/sonar-groovy#65]
After upgrading to SonarQube 9.0 i had to remove the sonar-groovy plugin because of the following error during startup:

```
java.lang.IllegalStateException: Fail to load plugin Groovy [groovy]
    at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:77)
    at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:575)
    at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
    at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)
    at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:120)
    at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
    at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:120)
    at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/profiles/ProfileDefinition
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
    at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
    at java.base/java.net.URLClassLoader$1.run(Unknown Source)
    at java.base/java.net.URLClassLoader$1.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.net.URLClassLoader.findClass(Unknown Source)
    at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
    at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
    at org.sonar.plugins.groovy.GroovyPlugin.define(GroovyPlugin.java:99)
    at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:67)
    ... 8 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.profiles.ProfileDefinition
    at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
    ... 22 common frames omitted
```

Had version 1.6 installed and also tried it with 1.7. Let me know if I can help..?

PS: see also at https://community.sonarsource.com/t/sq-crashes-after-upgrade-to-v9/45928/11

**Comment by TobiX** [comment]
Saw in the changelog that they removed many deprecated classes, so I'm not really surprised...

**Comment by TobiX** [comment]
@boardend Do you want to try a test build from #67? That change seems to fix the issue...

**Comment by boardend** [comment]
With `sonar-groovy-plugin-1.8-SNAPSHOT.jar` from Github SonarQube 9.0 is able to start again. Thank you!

**Comment by TobiX** [comment]
@boardend Thanks. I'll try to get a release out sometimes soon!
